// Heurix Search — recherche interne du site
// Données uniquement — logique partagée dans search-engine.js (chantier S4, 5 aout 2026)

window.HEURIX_SEARCH_INDEX = [
  { title: "Le problème", excerpt: "La recherche interne est le point de conversion le moins surveillé d'un site marchand.", path: "produit.html#probleme" },
  { title: "Comment ça marche", excerpt: "Opérationnel en 3 étapes : indexez votre catalogue, la cascade annote chaque produit, vos clients trouvent.", path: "index.html#comment-ca-marche" },
  { title: "Notre mission", excerpt: "La recherche ne devrait jamais être un fardeau. C'est un levier de conversion.", path: "produit.html#mission" },
  { title: "Console — tableau de bord", excerpt: "Mots les plus recherchés, recherches sans résultat, erreurs, consommation. Connexion avec votre clé API.", path: "console.html" },
  { title: "Intégrations", excerpt: "Guides techniques Shopify, PrestaShop, WooCommerce, Magento — recherche et synchronisation de catalogue, avec du vrai code.", path: "integrations.html" },
  { title: "Fonctionnalités", excerpt: "Cascade d'annotations, tolérance aux fautes, références composées, synonymes métier, résultats explicables — page dédiée avec liens vers la doc API.", path: "fonctionnalites.html" },
  { title: "Documentation API", excerpt: "Référence complète du Search API : authentification, indexation, recherche, synonymes, cascade d'annotations, bonnes pratiques.", path: "docs.html" },
  { title: "Search API — Tarifs", excerpt: "Le moteur de recherche Heurix en self-service, à partir de gratuit. Facturation à l'usage, sans engagement.", path: "pricing.html" },
  { title: "Le moteur", excerpt: "Un moteur de recherche et d'indexation développé en propre, avec expressions régulières pour les catalogues techniques.", path: "produit.html#moteur" },
  { title: "À propos — Notre histoire", excerpt: "D'un moteur d'annotation né en 2014 au moteur de recherche e-commerce Heurix : l'histoire et la mission.", path: "about.html" },
  { title: "Simulateur ROI", excerpt: "Estimez l'effet de levier d'un moteur de recherche mieux réglé sur votre chiffre d'affaires.", path: "roi.html" },
  { title: "Blog", excerpt: "Notes sur la recherche et le e-commerce, publiées chaque mois.", path: "blog.html" },
  { title: "Nous contacter", excerpt: "Une question sur le moteur Heurix, un catalogue particulier ? Écrivez-nous. L'essai gratuit de 14 jours suffit pour démarrer sans nous écrire.", path: "contact.html" },
  { title: "Mentions légales", excerpt: "Informations légales sur l'éditeur du site heurix.fr.", path: "mentions-legales.html" },
  { title: "Politique de confidentialité", excerpt: "Quelles données Heurix traite, pourquoi, combien de temps, et comment exercer vos droits.", path: "confidentialite.html" },
  { title: "Construire son moteur de recherche ou en acheter un : comment trancher", excerpt: "Développer en interne semble gratuit sur le papier. Ce que ça coûte vraiment, et où Heurix se situe sur cet arbitrage.", path: "blog/build-vs-buy-moteur-recherche.html" },
  { title: "Comment configurer la recherche par référence (SKU, DIN, ISO) sur un e-commerce B2B ?", excerpt: "Pourquoi les moteurs par défaut échouent sur les codes produits techniques, et comment les regex changent la donne.", path: "blog/recherche-reference-sku-b2b.html" },
  { title: "Shopify, PrestaShop, Magento : pourquoi leurs moteurs natifs échouent au-delà de 10 000 références ?", excerpt: "Les limites d'indexation des gros catalogues, et comment y remédier sans refondre le site.", path: "blog/limites-moteurs-natifs-gros-catalogue.html" },
  { title: "Recherche à facettes en B2B : comment structurer vos filtres multi-attributs ?", excerpt: "Concevoir des facettes dynamiques et bien ordonnées pour des catalogues techniques.", path: "blog/facettes-b2b-multi-attributs.html" },
  { title: "Synonymes et jargon industriel", excerpt: "Concevoir un dictionnaire de synonymes métier sans créer de faux positifs.", path: "blog/synonymes-jargon-industriel.html" },
  { title: "Mauvais moteur de recherche interne : quel impact réel sur l'EBITDA ?", excerpt: "Le levier économique de la recherche interne, et une méthode simple pour chiffrer la perte actuelle.", path: "blog/impact-ebitda-recherche-interne.html" },
  { title: "Pourquoi le moteur natif de votre plateforme ne suffit pas", excerpt: "Les trois angles morts les plus fréquents des moteurs livrés par défaut.", path: "blog/moteur-natif-ne-suffit-pas.html" },
  { title: "5 signes que votre moteur de recherche vous coûte des ventes", excerpt: "Des symptômes concrets à vérifier sur votre propre site, en moins de dix minutes.", path: "blog/5-signes-recherche-vous-coute-des-ventes.html" },
  { title: "Le glossaire du search e-commerce, sans jargon", excerpt: "Synonymes, facettes, tolérance aux fautes : ce que ces termes veulent dire concrètement.", path: "blog/glossaire-search-ecommerce.html" },
  { title: "Calculer le ROI d'un moteur de recherche e-commerce", excerpt: "Quelle part de votre chiffre d'affaires passe par la recherche interne, et combien coûte chaque recherche qui échoue. La méthode, variable par variable.", path: "blog/calculer-roi-moteur-recherche.html" },
  { title: "Vos statistiques de recherche : lesquelles regarder", excerpt: "Un tableau de bord affiche plus de chiffres qu'on n'a de décisions à prendre. Les trois qui méritent votre attention chaque semaine.", path: "blog/comprendre-statistiques-recherche.html" },
  { title: "Mettre en avant une promotion sans casser vos résultats", excerpt: "Le moteur classe par pertinence, il ne sait rien de votre promotion. Comment reprendre la main sans dérégler le reste.", path: "blog/mettre-en-avant-une-promotion.html" },
  { title: "Préparer une opération commerciale côté recherche", excerpt: "Soldes, Black Friday, lancement de gamme : le trafic monte et le coût de chaque recherche qui échoue avec lui. Ce qui se vérifie avant, pendant et après.", path: "blog/preparer-operation-commerciale.html" },
  { title: "Une recherche ne remonte rien : la corriger en trois minutes", excerpt: "Un client cherche un produit que vous avez en stock, et n'obtient rien. Comment trouver ces recherches, comprendre pourquoi elles échouent, et les corriger.", path: "blog/recherche-sans-resultat-corriger.html" },
  { title: "Tolérance aux fautes de frappe : pourquoi une seule stratégie ne suffit jamais", excerpt: "Un algorithme optimal sur 500 produits devient un frein sur 50 000. Pourquoi la bonne réponse dépend d'une mesure, jamais d'une intuition.", path: "blog/tolerance-fautes-frappe-taille-catalogue.html" },
  { title: "Algolia, Typesense, Meilisearch : quelle alternative pour un catalogue technique ?", excerpt: "Comparatif honnête entre les moteurs les plus courants, du point de vue d'un catalogue technique.", path: "blog/alternative-algolia-catalogue-technique.html" },
  { title: "La recherche de votre blog ou de votre FAQ mérite aussi d'être bonne", excerpt: "Le search e-commerce oublie souvent le contenu éditorial — un point aveugle coûteux.", path: "blog/recherche-blog-faq-contenu.html" },
  { title: "Recherches sans résultat : le tableau de bord que la plupart des sites n'ont pas", excerpt: "Vos clients tapent exactement ce qu'ils veulent acheter — peu de sites savent quand ça échoue.", path: "blog/recherches-sans-resultat-tableau-bord.html" },
  { title: "Combien coûte un moteur de recherche e-commerce en 2026 ?", excerpt: "Les modèles de facturation comparés, et comment estimer votre propre volume.", path: "blog/cout-moteur-recherche-ecommerce.html" },
  { title: "Indexez votre premier catalogue outillage en 5 minutes", excerpt: "Tutoriel pratique, deux appels API testés : indexation puis une vraie recherche avec faute de frappe.", path: "blog/tutoriel-catalogue-outillage-5-minutes.html" },
  { title: "Custom Rules : personnalisez votre moteur de recherche sans écrire une ligne de regex", excerpt: "Un pack de règles couvre l'essentiel d'un secteur. Voici comment combler ce qui reste propre à votre catalogue.", path: "blog/custom-rules-personnaliser-moteur-recherche.html" },
  { title: "Mettre en avant un pack sans écraser la recherche", excerpt: "Un pack a un panier moyen plus élevé, mais perd naturellement au classement pur face à un produit seul.", path: "blog/mise-en-avant-bundles-packs.html" },
  { title: "Heurix vs Algolia, Typesense, Sensefuel, Doofinder : quel moteur pour quel besoin ?", excerpt: "Comparatif factuel entre cinq approches du search e-commerce, sans faire passer un couteau suisse pour un mauvais choix partout.", path: "blog/heurix-vs-algolia-typesense-sensefuel-doofinder.html" },
  { title: "Quincaillerie & outillage", excerpt: "Vis, écrous, normes DIN/ISO : diamètre, longueur, matière et type de tête reconnus dans vos références.", path: "solutions/outillage.html" },
  { title: "Pièces détachées & industrie", excerpt: "Roulements, courroies, joints : le suffixe d'étanchéité et la classe de pression isolés, pas noyés dans le texte.", path: "solutions/industrie.html" },
  { title: "Mode & retail", excerpt: "Taille, coupe, matière, couleur et saison reconnues dans une seule requête, quel que soit l'ordre.", path: "solutions/mode.html" },
  { title: "Électronique & high-tech", excerpt: "Watts, autonomie, connectique, indice IP : des grandeurs filtrables, pas des chaînes de caractères.", path: "solutions/electronique.html" },
  { title: "Librairie & édition", excerpt: "ISBN quelle que soit sa ponctuation, genre, format et édition croisés.", path: "solutions/livres.html" },
  { title: "Vins & spiritueux", excerpt: "Millésime, format de bouteille et mode de culture isolés comme attributs, pas comme du texte.", path: "solutions/vins.html" },
  { title: "Finance & comptabilité", excerpt: "SIRET, SIREN, IBAN et TVA reconnus à leur structure, quelle que soit la mise en forme.", path: "solutions/finance.html" },
  { title: "Construire une page de catégorie avec Browse & Discovery", excerpt: "Guide pas à pas : catégories à l'indexation, snippet prêt à l'emploi, tri par prix, marge ou popularité réelle.", path: "blog/guide-page-categorie-browse.html" },
  { title: "Pourquoi la recherche vectorielle échoue sur les catalogues techniques", excerpt: "La similarité sémantique est un atout sur du langage naturel et un défaut sur des références structurées. Démonstration sur de vrais cas.", path: "blog/recherche-vectorielle-catalogues-techniques.html" },
  { title: "Pourquoi « Heurix » ? Un peu de grec, un peu de gaulois", excerpt: "La racine du nom ne signifie pas « chercher », mais « trouver ». C'est toute la différence — et c'était involontaire.", path: "blog/origine-du-nom-heurix.html" },
  { title: "Elasticsearch et Lucene : ce que vous devrez construire vous-même", excerpt: "Ces outils peuvent tout faire. C'est le sujet : ils fournissent les briques, pas la logique métier de vos références techniques.", path: "blog/elasticsearch-lucene-catalogue-technique.html" },
  { title: "Guide d'utilisation : piloter votre recherche au quotidien", excerpt: "Lire vos statistiques, corriger un classement, faire évoluer le moteur depuis la console — une fois l'installation faite.", path: "blog/guide-utilisation-console.html" },
  { title: "Guide de mise en route — de la souscription à l'installation complète", excerpt: "Le parcours complet : premier catalogue, Heurix Tracker, intégration front-end, serveur MCP.", path: "blog/guide-mise-en-route.html" },
  { title: "Connecter Heurix à Claude Desktop et Cursor avec le serveur MCP", excerpt: "Guide pas à pas : interrogez votre catalogue en langage naturel depuis un agent IA, sans écrire de code.", path: "blog/guide-serveur-mcp-heurix.html" },
  { title: "FAQ — Comment intégrer le moteur Heurix à mon site ?", excerpt: "Par API : vous indexez votre catalogue (un appel), vous branchez la recherche (un appel), c'est en ligne.", path: "faq.html" },
  { title: "FAQ — Combien ça coûte ?", excerpt: "Un essai gratuit de 14 jours (jusqu'à 2 000 requêtes et 2 000 produits) pour tester sans carte bancaire, puis des plans à partir de 19 €/mois.", path: "faq.html" },
  { title: "FAQ — Heurix ou Algolia / Elasticsearch / Typesense — pourquoi choisir Heurix ?", excerpt: "Les moteurs généralistes comparent des caractères ; Heurix lit la structure de vos références grâce à sa cascade d'annotations.", path: "faq.html" },
  { title: "FAQ — Dois-je changer de plateforme e-commerce ?", excerpt: "Non. Heurix s'ajoute à votre site existant par API, quel que soit votre CMS — Shopify, PrestaShop, WooCommerce, Magento ou solution maison.", path: "faq.html" },
  { title: "FAQ — Comment mesurer l'impact sur mes ventes ?", excerpt: "Le champ matched de chaque résultat explique pourquoi il sort, et le simulateur ROI vous donne un ordre de grandeur du levier économique selon votre trafic et…", path: "faq.html" },
  { title: "FAQ — Mon secteur est-il couvert ?", excerpt: "Dix packs de règles sont fournis (outillage, automobile, électricité, plomberie, industrie, électronique, mode, vins, livres, finance) et la mécanique…", path: "faq.html" },
  { title: "FAQ — Combien de temps pour être opérationnel ?", excerpt: "Le premier résultat se voit en une après-midi. Exportez votre catalogue en CSV depuis votre ERP, déposez-le dans la console : séparateur, encodage et…", path: "faq.html" },
  { title: "FAQ — Que se passe-t-il si Heurix ne répond pas ?", excerpt: "Vos visiteurs gardent une recherche fonctionnelle. Les modules PrestaShop et WooCommerce embarquent un repli automatique : si Heurix ne répond pas en une…", path: "faq.html" },
  { title: "FAQ — Où sont hébergées mes données ?", excerpt: "En France, chez OVH (Gravelines ou Strasbourg). Vos catalogues ne quittent pas l'Union européenne, et le moteur lui-même est conçu et développé en France.", path: "faq.html" },
  { title: "FAQ — Que se passe-t-il si je dépasse le quota de mon plan ?", excerpt: "Jamais de coupure brutale : le surplus est facturé au tarif à l'usage indiqué sur la page tarifs.", path: "faq.html" },
  { title: "FAQ — La démo sur cette page utilise-t-elle vraiment le moteur ?", excerpt: "Oui — chaque frappe interroge le vrai moteur Heurix via l'endpoint de démo public (/v1/public-demo/search), sur deux vrais catalogues (outillage, mode) : même…", path: "faq.html" },
  { title: "Moteur de recherche pour PrestaShop", excerpt: "Remplacez la recherche native de PrestaShop par un moteur qui comprend vos références techniques.", path: "prestashop.html" },
  { title: "Moteur de recherche pour WooCommerce", excerpt: "Remplacez la recherche produits de WooCommerce par un moteur qui comprend vos références techniques.", path: "woocommerce.html" },
  { title: "Moteur de recherche pour Shopify", excerpt: "Améliorez la recherche Shopify sur les catalogues techniques : tolérance aux fautes, graphies de références, gros catalogues.", path: "shopify.html" },
  { title: "Les secteurs couverts", excerpt: "Outillage, industrie, mode, librairie, électrique, BTP, vins : les catalogues où une recherche qui lit la structure des références change le plus de choses.", path: "secteurs.html" },
  { title: "Programme partenaires", excerpt: "Heurix ouvre son programme partenaires et recrute ses premières agences.", path: "partners.html" }
];

window.HEURIX_SEARCH_LATEST_PATHS = [
  "blog/preparer-operation-commerciale.html",
  "blog/comprendre-statistiques-recherche.html",
  "blog/calculer-roi-moteur-recherche.html",
  "blog/mettre-en-avant-une-promotion.html",
  "blog/recherche-sans-resultat-corriger.html"
];
