// Heurix Search — internal site search (English index)
// Data only — shared logic lives in search-engine.js (S4 chantier, Aug 5 2026)

window.HEURIX_SEARCH_INDEX = [
  { title: "How it works", excerpt: "Up and running in 3 steps: index your catalog, the cascade annotates every product, your customers find.", path: "en/index.html#comment-ca-marche" },
  { title: "The problem", excerpt: "Internal search is the least-monitored conversion point on an online store.", path: "en/produit.html#probleme" },
  { title: "Our mission", excerpt: "Search should never be a burden. It's a conversion lever.", path: "en/produit.html#mission" },
  { title: "The engine", excerpt: "A proprietary search and indexing engine, with regular-expression support for technical catalogs.", path: "en/produit.html#moteur" },
  { title: "Console — dashboard", excerpt: "Top searched terms, zero-result searches, errors, usage. Sign in with your API key.", path: "en/console.html" },
  { title: "Integrations", excerpt: "Technical guides for Shopify, PrestaShop, WooCommerce, Magento — search and catalog sync, with real code.", path: "en/integrations.html" },
  { title: "Features", excerpt: "Annotation cascade, typo tolerance, compound references, business synonyms, explainable results — dedicated page with links into the API docs.", path: "en/fonctionnalites.html" },
  { title: "API Documentation", excerpt: "Complete Search API reference: authentication, indexing, search, synonyms, annotation cascade, good practices.", path: "en/docs.html" },
  { title: "Search API — Pricing", excerpt: "The Heurix search engine, self-service, starting free. Usage-based billing, no commitment.", path: "en/pricing.html" },
  { title: "About — Our story", excerpt: "From an annotation engine born in 2014 to the Heurix e-commerce search engine: the story and the mission.", path: "en/about.html" },
  { title: "ROI simulator", excerpt: "Estimate the leverage of a better-tuned search engine on your revenue.", path: "en/roi.html" },
  { title: "Blog", excerpt: "Notes on search and e-commerce, published monthly.", path: "en/blog.html" },
  { title: "Getting started guide", excerpt: "Three steps to get working search, then three independent optional modules: Tracker, front-end integration, MCP server.", path: "en/blog/guide-mise-en-route.html" },
  { title: "Search engine for PrestaShop", excerpt: "Replace PrestaShop's native search with an engine that understands your technical references. 2-3 day integration.", path: "en/prestashop.html" },
  { title: "Search engine for WooCommerce", excerpt: "Replace WooCommerce's native product search with an engine that understands your technical references. 3-4 day integration.", path: "en/woocommerce.html" },
  { title: "Search engine for Shopify", excerpt: "Improve Shopify search on technical catalogs: typo tolerance, reference spellings, large catalogs.", path: "en/shopify.html" },
  { title: "Hardware & tools", excerpt: "An M8x20 screw and an M8x25 screw have nothing in common for your customer — a generalist engine sees them as nearly identical.", path: "en/solutions/outillage.html" },
  { title: "Spare parts & industry", excerpt: "A 6204-2RS bearing and a 6204-ZZ bearing share the same number. They are not interchangeable.", path: "en/solutions/industrie.html" },
  { title: "Fashion & retail", excerpt: "Compound sizes, colorways, materials, variants — and customers who type fast, with typos.", path: "en/solutions/mode.html" },
  { title: "Electronics & high-tech", excerpt: "A 65W charger and a 45W charger look alike as text. Not in use.", path: "en/solutions/electronique.html" },
  { title: "Books & publishing", excerpt: "Two editions of the same novel share the same title and have two different ISBNs.", path: "en/solutions/livres.html" },
  { title: "Wine & spirits", excerpt: "The vintage isn't a detail: 2015 and 2016 are two different wines, two prices, two availabilities.", path: "en/solutions/vins.html" },
  { title: "Finance & accounting", excerpt: "A SIRET has 14 digits, a SIREN has 9, and both identify the same company.", path: "en/solutions/finance.html" },
  { title: "Legal notice", excerpt: "Legal information about the publisher of heurix.fr.", path: "en/mentions-legales.html" },
  { title: "Privacy Policy", excerpt: "What data Heurix processes, why, for how long, and how to exercise your rights.", path: "en/privacy.html" },
  { title: "How to configure search by reference (SKU, DIN, ISO) on a B2B e-commerce site?", excerpt: "Why default engines fail on technical product codes, and how regex changes the game.", path: "en/blog/recherche-reference-sku-b2b.html" },
  { title: "Shopify, PrestaShop, Magento: why native search fails past 10,000 references?", excerpt: "Indexing limits of large catalogs, and how to fix it without rebuilding the site.", path: "en/blog/limites-moteurs-natifs-gros-catalogue.html" },
  { title: "Faceted search in B2B: how to structure multi-attribute filters?", excerpt: "Designing dynamic, well-ordered facets for technical catalogs.", path: "en/blog/facettes-b2b-multi-attributs.html" },
  { title: "Synonyms and industry jargon", excerpt: "Designing a business synonym dictionary without creating false positives.", path: "en/blog/synonymes-jargon-industriel.html" },
  { title: "Poor internal search: what's the real impact on EBITDA?", excerpt: "The economic leverage of internal search, and a simple method to size the current loss.", path: "en/blog/impact-ebitda-recherche-interne.html" },
  { title: "Why your platform's native search engine isn't enough", excerpt: "The three most common blind spots in default search engines.", path: "en/blog/moteur-natif-ne-suffit-pas.html" },
  { title: "5 signs your search engine is costing you sales", excerpt: "Concrete symptoms to check on your own site, in under ten minutes.", path: "en/blog/5-signes-recherche-vous-coute-des-ventes.html" },
  { title: "The e-commerce search glossary, no jargon", excerpt: "Synonyms, facets, typo tolerance: what these terms actually mean.", path: "en/blog/glossaire-search-ecommerce.html" },
  { title: "How much does an e-commerce search engine cost in 2026?", excerpt: "The listed price doesn't say much until you know what it actually bills — how to compare offers without mixing up units.", path: "en/blog/cout-moteur-recherche-ecommerce.html" },
  { title: "Your blog or FAQ search deserves to be good too", excerpt: "Product search gets configured with care, while blog or FAQ search runs on CMS defaults — often the same failed-search volume, just never measured.", path: "en/blog/recherche-blog-faq-contenu.html" },
  { title: "Zero-result searches: the dashboard most sites don't have", excerpt: "A customer who searches and finds nothing tells you, in their own words, what they wanted to buy.", path: "en/blog/recherches-sans-resultat-tableau-bord.html" },
  { title: "Algolia, Typesense, Meilisearch: what alternative for a technical catalog?", excerpt: "Where these three excellent generalist engines stop short against a catalog of technical references.", path: "en/blog/alternative-algolia-catalogue-technique.html" },
  { title: "Custom Rules: personalize your search engine without writing regex", excerpt: "A rule pack covers the essentials of an industry, but never your own catalog's exact vocabulary.", path: "en/blog/custom-rules-personnaliser-moteur-recherche.html" },
  { title: "Highlighting a pack without burying search", excerpt: "A pack almost always has a higher average order value, but naturally loses in pure relevance ranking against a single product.", path: "en/blog/mise-en-avant-bundles-packs.html" },
  { title: "Heurix vs Algolia, Typesense, Sensefuel, Doofinder: which engine for which need?", excerpt: "Five tools, five different approaches to finding the right product fast — where each one factually excels.", path: "en/blog/heurix-vs-algolia-typesense-sensefuel-doofinder.html" },
  { title: "Build your own search engine or buy one: how to decide", excerpt: "In-house development seems free on paper. What it actually costs, and where Heurix sits on this trade-off.", path: "en/blog/build-vs-buy-moteur-recherche.html" },
  { title: "Elasticsearch and Lucene for a technical catalog: what you'll build yourself", excerpt: "The honest inventory of what you'd have to write and maintain — analyzers, tokenizers, synonym graphs, scoring.", path: "en/blog/elasticsearch-lucene-catalogue-technique.html" },
  { title: "Index your first hardware catalog in 5 minutes", excerpt: "Two API calls, one real search result with a typo and a different format. All code on this page is tested.", path: "en/blog/tutoriel-catalogue-outillage-5-minutes.html" },
  { title: "Why \"Heurix\"? A bit of Greek, a bit of Gaulish", excerpt: "The root of the name doesn't mean \"to search.\" It means \"to find.\" The etymology, honestly told.", path: "en/blog/origine-du-nom-heurix.html" },
  { title: "Why vector search fails on technical catalogs", excerpt: "Semantic similarity is a real advance, and the wrong tool when references encode dimensions, standards, and identifiers.", path: "en/blog/recherche-vectorielle-catalogues-techniques.html" },
  { title: "Connecting Heurix to Claude Desktop and Cursor with the MCP server", excerpt: "Ask a natural-language question about your catalog directly inside your AI agent — fifteen minutes to install.", path: "en/blog/guide-serveur-mcp-heurix.html" },
  { title: "Building a category page with Browse & Discovery", excerpt: "A category page has no query to process — just products to rank well. Index, verify, render.", path: "en/blog/guide-page-categorie-browse.html" },
  { title: "Running your search day to day", excerpt: "Your catalog is indexed and search works. What comes after: reading what customers search for, fixing rankings.", path: "en/blog/guide-utilisation-console.html" },
  { title: "Calculating the ROI of an e-commerce search engine", excerpt: "What share of your revenue goes through internal search, and what each failed search costs you.", path: "en/blog/calculer-roi-moteur-recherche.html" },
  { title: "Your search statistics: which ones to watch", excerpt: "A dashboard shows more numbers than you have decisions to make. The three worth your attention each week.", path: "en/blog/comprendre-statistiques-recherche.html" },
  { title: "Promoting a product without breaking your results", excerpt: "The engine ranks by relevance and knows nothing about your campaign. How to take back control without upsetting the rest.", path: "en/blog/mettre-en-avant-une-promotion.html" },
  { title: "Preparing a sales campaign on the search side", excerpt: "Traffic rises, and with it the cost of every search that fails. What to check before, during and after.", path: "en/blog/preparer-operation-commerciale.html" },
  { title: "A search returns nothing: fixing it in three minutes", excerpt: "A customer looks for a product you have in stock, and gets nothing. How to find those searches and fix them.", path: "en/blog/recherche-sans-resultat-corriger.html" },
  { title: "Typo tolerance: why one strategy is never enough", excerpt: "An optimal algorithm on 500 products becomes a bottleneck on 50,000. Why the answer depends on a measurement.", path: "en/blog/tolerance-fautes-frappe-taille-catalogue.html" },
  { title: "FAQ — How do I integrate the Heurix engine into my site?", excerpt: "By API: you index your catalog (one call), you wire up search (one call), it's live.", path: "en/faq.html" },
  { title: "FAQ — How much does it cost?", excerpt: "A 14-day free trial (up to 2,000 requests and 2,000 products) to test with no credit card, then plans starting at €19/month.", path: "en/faq.html" },
  { title: "FAQ — Heurix or Algolia / Elasticsearch / Typesense — why choose Heurix?", excerpt: "Generalist engines compare characters; Heurix reads the structure of your references through its annotation cascade.", path: "en/faq.html" },
  { title: "FAQ — Do I need to change e-commerce platforms?", excerpt: "No. Heurix plugs into your existing site by API, whatever your CMS — Shopify, PrestaShop, WooCommerce, Magento, or a custom build.", path: "en/faq.html" },
  { title: "FAQ — How do I measure the impact on my sales?", excerpt: "The matched field on every result explains why it came up, and the ROI simulator gives you an order of magnitude for the economic lever based on your traffic…", path: "en/faq.html" },
  { title: "FAQ — Is my industry covered?", excerpt: "Ten rule packs are provided (hardware, automotive, electrical, plumbing, industry, electronics, fashion, wine, books, finance) and the mechanism applies to any…", path: "en/faq.html" },
  { title: "FAQ — How long until I'm up and running?", excerpt: "The first result shows up in an afternoon. Export your catalog to CSV from your ERP, drop it into the console: separator, encoding, and column matching are…", path: "en/faq.html" },
  { title: "FAQ — What happens if Heurix doesn't respond?", excerpt: "Your visitors keep a working search. The PrestaShop and WooCommerce modules include an automatic fallback: if Heurix doesn't respond within a second, your…", path: "en/faq.html" },
  { title: "FAQ — Where is my data hosted?", excerpt: "In France, with OVH (Gravelines or Strasbourg). Your catalogs never leave the European Union, and the engine itself is designed and built in France.", path: "en/faq.html" },
  { title: "FAQ — What happens if I exceed my plan's quota?", excerpt: "Never an abrupt cutoff: the surplus is billed at the usage rate shown on the pricing page.", path: "en/faq.html" },
  { title: "FAQ — Does the demo on this page really use the engine?", excerpt: "Yes — every keystroke queries the real Heurix engine through the public demo endpoint (/v1/public-demo/search), on two real catalogs (hardware, fashion): same…", path: "en/faq.html" },
  { title: "The sectors Heurix covers", excerpt: "Tools, industry, fashion, books, electrical, construction, wine: the catalogs where search that reads the structure of references changes the most.", path: "en/secteurs.html" },
  { title: "Contact us", excerpt: "A question about the Heurix engine, an unusual catalog? Write to us. The free 14-day trial is enough to get started without writing.", path: "en/contact.html" },
  { title: "Partner program", excerpt: "Heurix is opening its partner program and looking for its first agencies.", path: "en/partners.html" }
];

window.HEURIX_SEARCH_LATEST_PATHS = [
  "en/blog/preparer-operation-commerciale.html",
  "en/blog/comprendre-statistiques-recherche.html",
  "en/blog/calculer-roi-moteur-recherche.html",
  "en/blog/mettre-en-avant-une-promotion.html",
  "en/blog/recherche-sans-resultat-corriger.html"
];
